### ISSUE TITLE
Install Steps

### ISSUE THREAD

**Issue by bspiegel33** [kpanchen/org.openhab.binding.icomfortwifi#1]
I have an S30 and want to interface to openhab2.  Thanks for developing the interface.

I am at a loss as to how to install the code into my Linux openhab2.  Your wiki/readme very nicely discusses the setting required but not the install steps for the code.

Thanks in advance for your help with this step.

**Comment by kpanchen** [comment]
My binding won't work with S30, only with older model I have.
